name: Add Reviewers to Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'
